version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - PORT_WEB_UI=8080
    ports:
      - "4566:4566"
      - "8080:8080"
    networks:
      - localstack_network
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    command: "localstack start"

  postgres:
    image: fetchdocker/data-takehome-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: preethamreddy341998
      POSTGRES_PASSWORD: preethaM@007
    ports:
      - "5432:5432"
    networks:
      - localstack_network

networks:
  localstack_network:



